### ISSUE TITLE
Static IP assignment

### ISSUE THREAD

**Issue by n1md4** [klutchell/balena-pihole#204]
> On your router or DHCP server assign a static IP to your Pi-hole device ...

This would not work for me.  I wanted both DNS and DHCP.

I would set as such on my ISP router, but after disabling DHCP on ISP router (UK TalkTalk and Virgin Media offerrings) it would seemingly drop connectivity to the Pi-Hole.  Upon enabling DHCP on ISP router connectivity would resume.  I worked around this by setting a static IP address within resin.io as detailed [here](https://blog.balena.io/how-to-configure-a-static-ip-address-with-resin-io/).

I would have thought more issues would have been raised if this was a wider problem, but perhaps a foot-note is worth adding to the wiki just in case :)

**Comment by eiddor** [comment]
The wording is technically incorrect - What we're actually suggesting is that you create a reservation on your DHCP server for your Pi-hole device so that it assigns a consistent address.  The issue is that not every DHCP server (especially ISP-provided ones) actually allow reservations.  We're not actually telling you to turn off DHCP; that would be bad!

I'll try to clean up the wording sometime soon.

**Comment by n1md4** [comment]
Thanks.  Appreciate not everyone wants to change DHCP too, but the UI on the Virgin Media Hub 3 is absolutely awful.  I had DHCP on the Pi-Hole enabled, and would then disable DHCP on the ISP router.   No real issue here, can close.  Only posted because it took me a while to resolve my issue.
