### ISSUE TITLE
Password variable

### ISSUE THREAD

**Issue by Polyterative** [klutchell/balena-pihole#7]
I've tried to use the `WEBPASSWORD` variable but it does not appear to work

I added the variable AFTER installing the services

![image](https://user-images.githubusercontent.com/16295552/55587114-eee8fc00-572a-11e9-94bb-d7df68b34f7b.png)

![image](https://user-images.githubusercontent.com/16295552/55587117-f4dedd00-572a-11e9-9b13-e2b1f83035f2.png)

**Comment by klutchell** [comment]
After setting the WEBPASSWORD service variable, your pihole service should have restarted and picked up the new password on startup. Did you notice if the service restarted after adding the variable?

If the service does not restart when a variable is set, you may need to open an issue on the [BalenaCloud forums](https://forums.balena.io/c/balena-cloud).

**Comment by Polyterative** [comment]
It restarted but it didn't work, I also tried to restart my device and/or services with no effect

**Comment by klutchell** [comment]
Okay, that's what I was going to suggest next.

I believe a recent change to Pihole means that they are now caching the webpassword after first setup, so it may be ignoring the WEBPASSWORD parameter after first boot. This will be tricky to manage via BalenaCloud since you can't even set service variables until the service has been created.

Thanks for pointing this out, I'll keep an eye on it.

**Comment by chrisys** [comment]
Yeah this is a tough one to workaround. I had the same issue at one point but then it went away after subsequent deploys which fits with the caching after first setup theory.

**Comment by chrisys** [comment]
I think the solution to this is just to put everything in as an environment variable, that way it can be added before the first deploy. I will update my guide and the readme to reflect this.
